# Generated by Django 5.0.3 on 2024-03-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date'], 'verbose_name': 'مخاطب', 'verbose_name_plural': 'مخاطبین'},
        ),
    ]
